### ISSUE TITLE
'build --target' Delimiter Character

### ISSUE THREAD

**Issue by riweston** [jlucktay/stack#56]
Currently the delimiter character when targeting multiple components is `;`, from the shell this triggers a new line without wrapping the command in quotes or escaping this character.

Could the delimiter character from the command line be changed to a `,` - this is how you would input multiple values into a parameter in Powershell but open to other suggestions if you think another character makes sense

**Comment by jlucktay** [comment]
@riweston fire off `brew upgrade jlucktay/tap/stack` and see how `v0.7.1` goes 🚀
